### ISSUE TITLE
.env.prod里添加了默认配置.启动还是报错了

### ISSUE THREAD

**Issue by Kiana1314** [MinatoAquaCrews/nonebot_plugin_antiflash#1]
.env.prod里添加了默认配置.
ANTI_FLASH_ON=true                          # 全局开关
ANTI_FLASH_GROUP=[ ] # 默认开启的群聊，但可通过指令开关
ANTI_FLASH_PATH="your-path-to-config.json"  # 配置文件路径，默认同插件代码路径

启动还是报错了
07-04 14:27:28 [ERROR] nonebot | Failed to import "nonebot_plugin_antiflash"
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\bot\NB\venv\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\bot\NB\venv\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\bot\NB\venv\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\bot\NB\venv\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\bot\NB\venv\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\bot\NB\venv\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\bot\NB\venv\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "C:\bot\NB\venv\lib\site-packages\nb_cli\handlers\deploy.py", line 20, in run_bot
    module = importlib.import_module(module_name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_m
odule
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\bot\NB\LittlePaimon\.\bot.py", line 26, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "C:\bot\NB\venv\lib\site-packages\nonebot\plugin\load.py", line 119, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\bot\NB\venv\lib\site-packages\nonebot\plugin\load.py", line 53, in load_all_plugins
    return manager.load_all_plugins()
  File "C:\bot\NB\venv\lib\site-packages\nonebot\plugin\manager.py", line 172, in load_all_plugins
    return set(
  File "C:\bot\NB\venv\lib\site-packages\nonebot\plugin\manager.py", line 173, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\bot\NB\venv\lib\site-packages\nonebot\plugin\manager.py", line 144, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_m
odule
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\bot\NB\venv\lib\site-packages\nonebot\plugin\manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\bot\NB\venv\lib\site-packages\nonebot_plugin_antiflash\__init__.py", line 7, in <module>
    from .config import handler
  File "C:\bot\NB\venv\lib\site-packages\nonebot_plugin_antiflash\config.py", line 83, in <module>
    handler = AntiFlashHandler(config)
  File "C:\bot\NB\venv\lib\site-packages\nonebot_plugin_antiflash\config.py", line 29, in __init__
    with open(self.path, "w", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'your-path-to-config.json\\config.json'

**Comment by KafCoppelia** [comment]
哥啊`ANTI_FLASH_PATH="your-path-to-config.json" `路径要改成自己实际的路径
